// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzNvwzkGDiW666xsJvENPJNVGl7HC9JE',
    appId: '1:1077139693374:web:3dc88186108dbc4ed3d66f',
    messagingSenderId: '1077139693374',
    projectId: 'hr-system-be0e2',
    authDomain: 'hr-system-be0e2.firebaseapp.com',
    storageBucket: 'hr-system-be0e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCX756KgRi0_3tNUyD3_5lymoBenvkYus',
    appId: '1:1077139693374:android:776b8a1a17740bbfd3d66f',
    messagingSenderId: '1077139693374',
    projectId: 'hr-system-be0e2',
    storageBucket: 'hr-system-be0e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAzx15-vz7mOtojJQIpXw9HwxGLsrQik',
    appId: '1:1077139693374:ios:c1af6781ca623a8ed3d66f',
    messagingSenderId: '1077139693374',
    projectId: 'hr-system-be0e2',
    storageBucket: 'hr-system-be0e2.appspot.com',
    iosClientId: '1077139693374-v1cpdkifbvcbj61n33h5c25ockr1aqgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.inxeeHrApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAzx15-vz7mOtojJQIpXw9HwxGLsrQik',
    appId: '1:1077139693374:ios:c1af6781ca623a8ed3d66f',
    messagingSenderId: '1077139693374',
    projectId: 'hr-system-be0e2',
    storageBucket: 'hr-system-be0e2.appspot.com',
    iosClientId: '1077139693374-v1cpdkifbvcbj61n33h5c25ockr1aqgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.inxeeHrApplication',
  );
}
